stages:
  - package

.tags: &tags
  tags:
    - librem5

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install build-essential wget ca-certificates gnupg
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - apt-get -y update
  - apt-get -y build-dep .

build-debian-package:
  <<: *tags
  image: debian:buster
  stage: package
  script:
    - dpkg-buildpackage -uc -us
